services:

  bot:
    build: .
    environment:
      - SELENOID_URL=http://selenoid:4444/wd/hub
      - OUTPUT_DIR=/app/output
    volumes:
      - ./output:/app/output
    networks:
      - connect

networks:
  connect:
    external: true
